[project]
name = "manul"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tomoya Sawada", email = "stomoya0110@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []
dynamic = ["version"]

[tool.maturin]
module-name = "manul._manul"
manifest-path = "crates/manul_pyo3/Cargo.toml"
python-packages = ["manul"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "crates/**/*.rs" }, { file = "crates/**/Cargo.toml" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "natsort>=8.4.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]

[tool.ruff]
fix = true
line-length = 120
indent-width = 4
output-format = "concise"

target-version = "py311"
src = ["src", "tests"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "F405"]
"*.pyi" = ["F401"]

[tool.ruff.lint]
select = [
    # "FAST",  # FastAPI apps.
    "YTT",    # flake8 sys.version usage
    "ANN",    # flake8 function annotations
    "ASYNC",  # flake8 async
    "FBT",    # flake8 boolean trap
    "B",      # flake8 bugbear
    "A",      # flake8 builtins
    "COM",    # flake8 commas
    "C4",     # flake8 comprehensions
    "DTZ",    # flake8 datetimez
    "T10",    # flake8 debugger
    "T20",    # flake8 print
    "EM",     # flake8 error message
    "FA",     # flake8 future annotations
    "ISC",    # flake8 implicit str concat
    "LOG",    # flake8 logging
    "G",      # flake8 logging format
    "PIE",    # flake8 pie
    "PYI",    # flake8 pyi
    "PT",     # flake8 pytest
    "RSE",    # flake8 raise
    "RET",    # flake8 return
    "SIM",    # flake8 simplify
    "SLOT",   # flake8 slots
    "TID252", # flake8 tidy imports -- relative imports from parent module
    # "TID254", # flake8 tidy imports -- lazy import -- This ruleset is in preview
    # "TID255", # flake8 tidy imports -- lazy import resolved immediately -- This ruleset is in preview
    "TC",     # flake8 type checking
    "ARG",    # flake8 unused arguments
    "PTH",    # flake8 use pathlib
    "FLY",    # flynt
    "I",      # isort
    "C90",    # McCabe complex structure
    "NPY",    # numpy
    "N",      # pep8 -- naming
    "PERF",   # Perlint
    "E",      # pycodestyle -- error
    "W",      # pycodestyle -- warning
    # "DOC",    # pydoclint -- This ruleset is in preview
    "D",      # pydocstyle
    "F",      # pyflakes
    "PGH003", # pygrep-hooks -- blanket type ignore
    "PGH004", # pygrep-hooks -- blanket noqa
    "PL",     # pylint
    "UP",     # pyupgrade
    "FURB",   # refurb
    "RUF",    # ruff
    "TRY",    # tryceratops
]
ignore = [
    "SIM108",  # if: a = ...; else: a = ... -> a = ... if else ...
    "PYI021",  # docstring in .pyi.
    "NPY002",  # use np.random.Generator. Most programs still rely on np.random.seed().
    "D105",    # undocumented magic method
    "D107",    # undocumented public __init__
    "D205",    # missing blank line after summary -- ignored to support multiline summary.
    "PLC2701", # import private name -- patching stuff in third party packages requires this. I do this relatively frequently.
    "PLR0913", # too many arguments -- Setting max value isn't solving anything. Just remove this.
    "PLR0917", # too many positional arguments -- Same as above
    "C408",    # dict().
    "COM812",  # missing trailing comma -- might conflict with formatter
]
# flake8-annotations = { allow-star-arg-any = true }  # TODO: decide if we need this.
mccabe = { max-complexity = 14 }  # Taken from pydantic. We'll see if this fits me.
pydocstyle = { convention = 'google' }
future-annotations = true

fixable = ["ALL"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
    "-vv",
    "-s",
    "-ra",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=xml:reports/coverage.xml",
    "--junitxml=reports/pytest.xml"
]

[tool.coverage.run]
source = ["src"]
omit = []

[tool.coverage.report]
exclude_also = [
    "@(abc\\.)?abstractmethod",
    'raise\sNotImplementedError',
    '@(typing\.)?overload',
    'class .*\bProtocol\):',
    '(typing\.)?.assert_never',
]
